### ISSUE TITLE
Author: I want my posts to have categories

### ISSUE THREAD

**Issue by adamva** [CMPUT-404-2023-Not-Found/CMPUT404-project-socialdistribution#117]
- [ ] Posts can have categories
- [ ] Posts return their categories
- [ ] Categories should be an additional model attached to the Post model

*Refer to API scheme spec for how categories should look*

Reference of [sub-models in Django](https://stackoverflow.com/questions/1126642/how-would-you-inherit-from-and-override-the-django-model-classes-to-create-a-list)

**Comment by MichaelLsh** [comment]
For now, categories are optional. A post can have at most two categories. 
Give default legit default value to categories if the author chooses not to use them.

**Comment by MichaelLsh** [comment]
"Happy-path testing needed for post categories"
